data(condor)
data(dugong)
data(panda)
condor[, sapply(condor, is.numeric)] <- round(condor[, sapply(condor, is.numeric)], 0)
dugong[, sapply(dugong, is.numeric)] <- round(dugong[, sapply(dugong, is.numeric)], 0)
panda[, sapply(panda, is.numeric)] <- round(panda[, sapply(panda, is.numeric)], 0)
write.table(condor, file = "condor.txt", sep = " ", row.names = FALSE, col.names = TRUE, quote = FALSE)
write.table(dugong, file = "dugong.txt", sep = " ", row.names = FALSE, col.names = TRUE, quote = FALSE)
write.table(panda, file = "panda.txt", sep = " ", row.names = FALSE, col.names = TRUE, quote = FALSE)
